### ISSUE TITLE
Failing to use with create-react-app because of ".mjs"

### ISSUE THREAD

**Issue by gustavopch** [lukeed/httpie#10]
Hey. The lib currently cannot be used by create-react-app applications because it's using `.mjs` which appears to be unsupported by CRA (see https://twitter.com/dan_abramov/status/1042884207666704390?lang=en). Not sure if you will want to support CRA, but I thought you'd want to know this.

**Comment by gustavopch** [comment]
But the lib is actually targeted to Node.js, not for the browser, right? I missed this detail :smile:

**Comment by lukeed** [comment]
Yup, that's true :) Your CRA shouldn't ever need to know about httpie. 

FWIW, it looks like next version of CRA will cooperate with `.mjs` again. An upstream fix was applied to webpack & they'll be shipping the version of webpack _with_ the fix.
