### ISSUE TITLE
🙈 Ignore package-lock.json and yarn.lock

### ISSUE THREAD

**Issue by charlyx** [lukeed/httpie#13]
Following up the conversation from #11 about `package-lock.json`

May I suggest you to add lock files in `.gitignore`? If you agree, I'd be happy to make a PR.

**Comment by lukeed** [comment]
Haha, sure! There's already `*.lock` in the file, so if you can add `*-lock.json` above it, that'd be great~!

**Comment by charlyx** [comment]
Oh ok! Since you're using `npm` in your `pretest` script I assumed that you were using npm and not yarn.
I should have taken a look at your `.gitignore` file... Thanks for your answer 😄

**Comment by lukeed** [comment]
No problem! It's npm on CI because I don't want to deal with setting up yarn just to run a command or two 👍
