### ISSUE TITLE
If host is offline

### ISSUE THREAD

**Issue by mauriciolucas22** [lukeed/httpie#20]
If my host is offlne when post/get ? how to get error status ?

**Comment by mauriciolucas22** [comment]
"statusMessage":"Not Found","statusCode":404,"headers":{"server":"nginx/1.10.1","date":"Wed, 06 Nov 2019 12:59:01 GMT","content-length":"3","connection":"close"},"data":"404"

**Comment by lukeed** [comment]
Hey, I'm not sure what you're asking?

You'll get an error if the server you're hitting is offline. Whether that error is a 404, 400, 500, ...502 is completely up to the server. But _because_ it almost certainly will be a >400 status code, `httpie` will present that information to you in the `catch` block of your handler.

There's nothing it does (or can do) to influence the outcome/response of a dead server.

Hope that helps – if I misunderstood something please lemme know.
Thanks!
