### ISSUE TITLE
react-native compatibility (Android)

### ISSUE THREAD

**Issue by endel** [lukeed/httpie#21]
Hi there,

I've received this bug report on my project that uses `httpie@^2.0.0-next.2`: https://github.com/colyseus/colyseus.js/issues/55

I believe it's related to httpie but haven't inspected super deep yet. There is also a similar issue reported on `axios` repository here: https://github.com/axios/axios/issues/1938

I hope to find a solution and create a PR soon

**Comment by endel** [comment]
Hi @lukeed, I just noticed that you've already fixed this here: https://github.com/lukeed/httpie/commit/a29769f6edf3dd430dffb5743d53f9d1b37f6c47

Do you mind publishing this version to NPM? I believe it could be `2.0.0` without tags this time. I've been using it for quite some time and it's pretty stable.

Cheers!

**Comment by lukeed** [comment]
Hey, thank you for following up :)

Funny, I thought I had published those changes now.
In any event, `httpie@2.0.0-next.3` is now published (with `next` tag).

I need to find time this holiday break to finish the last batch of documentation and testing.

Thanks again 🎉

**Comment by endel** [comment]
Thanks for the fast reply @lukeed!

I'm not a React Native expert but I found a strange behavior:
- Created a React Native app (Expo)
- Use `colyseus.js` (with the new `httpie@2.0.0-next.3 ` version)
- Open the Expo app from Android
- The error appears (`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference `)
- If I open the `node_modules/httpie/dist/httpie.esm.js` file, and save it (without any changes on it) - it triggers a rebuild and reloads on Android Expo app, and the error doesn't show anymore 

😨

**Comment by lukeed** [comment]
I've no idea. I've never touched RN or its tools (and don't plan to).

Is that consistent? Is there a build cache that needs to be invalidated?

**Comment by endel** [comment]
Right, sorry to bother, you're correct, I've used `expo --clear` and the error is gone :) 

Thanks again @lukeed! ❤️

**Comment by lukeed** [comment]
Not a problem at all, glad it works!

**Comment by gabimoncha** [comment]
@lukeed Hi, somehow I'm getting this error 2 years later :(
Tried `expo start --clear` with no luck

**Comment by lukeed** [comment]
Still never used RN, sorry. Not sure if `expo --clear` and `export start --clear` are the same thing though
