### ISSUE TITLE
How to Timeout requests

### ISSUE THREAD

**Issue by DavidWells** [lukeed/httpie#23]
Hey there!

How do I timeout requests? 

I can't get this to work:

```
const httpsResp = await get(httpsUrl, { timeout: 2000 })
```

It looks like https://github.com/lukeed/httpie/pull/17 wasn't merged in.

**Comment by lukeed** [comment]
Hey,

What version are you using? The `timeout` option only exists in the `@next` version and is available across all 3 modes

**Comment by DavidWells** [comment]
I'm on `"httpie": "^1.1.2",`

So `npm install httpie@next` will have timeout? 😃

**Comment by lukeed** [comment]
Yup! For browser & Node
