### ISSUE TITLE
ESM module for both Node.js and the Browser?

### ISSUE THREAD

**Issue by endel** [lukeed/httpie#33]
Hi @lukeed, it's me again! How're you doing? 😄 

(Thanks for the help you gave here a few months ago 🥳  https://github.com/colyseus/colyseus.js/issues/64#issuecomment-646386869)

Continuing that discussion -  I see you're using the same pattern for every project of yours - but they don't seem to work nicely with `vite` / `snowpack` / `webpack` (v5) - I've created a repository reproducing it here: https://github.com/endel/esm-browser-node

ESM modules seem to be finally rolling out with modern frontend tooling, and it seems we can't have a `"browser"` field, or anything like it. That makes it difficult for us maintainers to keep a module compatible with as many environments as possible. This seems to be a problem in the ecosystem.

I also created the same issue here trying to get some answers: https://github.com/vitejs/vite/issues/1154

Thanks for your support! 🙏

**Comment by lukeed** [comment]
Hey, I've left a comment on the webpack issue. Looks like Vite is heading in a good direction. I've spoken to Snowpack before, but they're following webpack's lead here.

At time of writing, everything in `httpie@next` worked out of the box. It still does/can when it's your own Rollup/webpack configuration. But these done-for-you opinionated wrappers include decisions & abstractions that make it hard(er) for you to reach in and tweak what needs to be tweaked.

The good news is that until these fixes land in the correct places, you can always alias and/or skip the top-level `httpie` import in favor of the module that you need. So, for example, in an opinionated webpack config/tool, I ended up keeping my `httpie` import and then did stuff like this:

```js
resolve: {
  alias: {
    // ...
    'httpie': isNode // via ENV or flag -- custom
      ? require.resolve('httpie/node/index.mjs') 
      : require.resolve('httpie/fetch/index.mjs')
```

And then, of course, you could always specify a submodule import directly, but that makes isomorphic usage (as in your case) harder:

```diff
--import { send } from 'httpie';
++import { send } from 'httpie/fetch';
```

I hope that helps enough for the time being!
Please ping me in any issues/discussions you think I can be helpful in. 

As it stands, these are opinions/configs that are outside my reach (and misguided tbh). The current `httpie` exports work well with the underlying tools, but the decisions on top are the blockers. As a default behavior, I understand the concern(s) re: `browser` based on how it's been loosely defined in the past, but your idea of detecting `.mjs` is a good first-step that should already be done. Aside from that, tools like these should always offer a way to customize those `mainFields` order. 

Closing this here, but please let me know where else I can chime in.
Thanks!
