### ISSUE TITLE
npm "readme" is totally blank

### ISSUE THREAD

**Issue by saibotsivad** [lukeed/httpie#37]
Been using `httpie` for a while, and just noticed today that [on npm](https://www.npmjs.com/package/httpie) the whole readme section is blank:
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/91254/143318846-29c6aaba-901b-4317-aebb-ccfe6ebf7c99.png">

I believe this is because npm expects capitalized `README.md` and you've got lower cased `readme.md`.

Trying to search on npm for `httpie` without actually using `httpie` (e.g. "lightweight http" etc.) doesn't show any results, so I'd wager that their search index uses the `README.md` content.

Not a critical issue of course, just thought I'd drop you a note.

**Comment by TehShrike** [comment]
I see a readme on npm today: https://www.npmjs.com/package/httpie

I never uppercase `README` and npm has always displayed my content fine 😅 

I wonder if npm was just having issues that day

**Comment by saibotsivad** [comment]
Huh, very interesting! Procrastination wins, this time 😆
