### ISSUE TITLE
Headers are not being send

### ISSUE THREAD

**Issue by Siilwyn** [lukeed/httpie#4]
After bashing my head for something simple not working I found out `httpie` does not send the headers passed in the options. I don't want to be rude but reading the code to find this out was pretty hard with all the single letter variables.

**Comment by lukeed** [comment]
Oops, sorry, fixing it now! It was lost in a quick refactor I did here: https://github.com/lukeed/httpie/commit/5aa37248f49f4961c3b81a90998e58a1a0f09e46

That's the code I'd been using for years & know it works. Sorry for the mishap & inconvenience.

And no worries – I don't find it rude. It's coding style, plus there are only two single-letter variables & the whole function is < 50 lines. In different conditions I would agree!

**Comment by lukeed** [comment]
Available in `0.3.0`, thanks again
