### ISSUE TITLE
Nameclash

### ISSUE THREAD

**Issue by slavaGanzin** [lukeed/httpie#5]
Hello

https://httpie.org/ is python http library and cli client.
I think you better change name, because it will create troubles for googling your/theirs library

**Comment by lukeed** [comment]
Hey, thanks I've been told a few times already. I didn't know until yesterday.

I think it's fine though because there can only be one on npm. If it can't be found thru Google search, ce la vie. I'd rather share my stuff than make sure it's found/used.

Thanks for your concern though!

**Comment by jkbrzt** [comment]
Dude, seriously.

![dyvqqe5wkae-h6c](https://user-images.githubusercontent.com/326885/52166176-1eb75b80-270a-11e9-9614-f80203e78a8b.jpg)

**Comment by janbaer** [comment]
This was the first which came into my mind when I read about this project here? **HTTPie** is well known and often used as an alternative for **curl**. So I would also suggest searching for another project name to avoid naming conflicts. I had similar problems with one of my projects and I wished that I knew it earlier.

By the way when you Google for *httpie*, it's the first search result, so I wonder that you didn't know it before.
